"""Initial migration

Revision ID: b5ce7e9a588c
Revises: 
Create Date: 2025-07-15 23:39:43.756378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5ce7e9a588c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingredient',
    sa.Column('IngredientId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('IsAllergen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('IngredientId')
    )
    op.create_table('Recipe',
    sa.Column('RecipeId', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Ingredients', sa.Text(), nullable=False),
    sa.Column('CookingTime', sa.Integer(), nullable=True),
    sa.Column('ImageUrl', sa.String(length=2048), nullable=True),
    sa.Column('RecipeUrl', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('RecipeId')
    )
    op.create_table('Tags',
    sa.Column('TagId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('TagId')
    )
    op.create_table('User',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('RegistrationDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Preferences',
    sa.Column('PreferenceId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Allergen', sa.String(length=100), nullable=True),
    sa.Column('DietaryPreference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PreferenceId')
    )
    op.create_table('RatingsFeedback',
    sa.Column('RatingId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecipeId', sa.Integer(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.Column('Comment', sa.Text(), nullable=True),
    sa.Column('FeedbackDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RecipeId'], ['Recipe.RecipeId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('RatingId')
    )
    op.create_table('RecipeTag',
    sa.Column('RecipeId', sa.Integer(), nullable=False),
    sa.Column('TagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RecipeId'], ['Recipe.RecipeId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagId'], ['Tags.TagId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RecipeId', 'TagId')
    )
    op.create_table('SavedRecipe',
    sa.Column('SavedRecipeId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('RecipeId', sa.Integer(), nullable=False),
    sa.Column('SavedDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RecipeId'], ['Recipe.RecipeId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SavedRecipeId')
    )
    op.create_table('SearchHistory',
    sa.Column('SearchId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Keywords', sa.String(length=255), nullable=False),
    sa.Column('SearchDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SearchId')
    )
    op.drop_table('searchhistory')
    op.drop_table('ratingsfeedback')
    op.drop_table('tags')
    op.drop_table('preferences')
    op.drop_table('recipetag')
    op.drop_table('savedrecipe')
    op.drop_table('ingredient')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Email'))

    op.drop_table('user')
    op.drop_table('recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('RecipeId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Ingredients', mysql.TEXT(), nullable=False),
    sa.Column('CookingTime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ImageUrl', mysql.TEXT(), nullable=True),
    sa.Column('RecipeUrl', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('RecipeId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('UserId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RegistrationDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Email'), ['Email'], unique=True)

    op.create_table('ingredient',
    sa.Column('IngredientId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('IsAllergen', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('IngredientId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('savedrecipe',
    sa.Column('SavedRecipeId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('RecipeId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SavedDate', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['RecipeId'], ['recipe.RecipeId'], name=op.f('savedrecipe_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['user.UserId'], name=op.f('savedrecipe_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SavedRecipeId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipetag',
    sa.Column('RecipeId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TagId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['RecipeId'], ['recipe.RecipeId'], name=op.f('recipetag_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TagId'], ['tags.TagId'], name=op.f('recipetag_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RecipeId', 'TagId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('preferences',
    sa.Column('PreferenceId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Allergen', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DietaryPreference', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['user.UserId'], name=op.f('preferences_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PreferenceId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tags',
    sa.Column('TagId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('TagId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ratingsfeedback',
    sa.Column('RatingId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RecipeId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Comment', mysql.TEXT(), nullable=True),
    sa.Column('FeedbackDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('(`Rating` between 1 and 5)', name=op.f('ratingsfeedback_chk_1')),
    sa.ForeignKeyConstraint(['RecipeId'], ['recipe.RecipeId'], name=op.f('ratingsfeedback_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['user.UserId'], name=op.f('ratingsfeedback_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('RatingId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('searchhistory',
    sa.Column('SearchId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Keywords', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('SearchDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['user.UserId'], name=op.f('searchhistory_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SearchId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('SearchHistory')
    op.drop_table('SavedRecipe')
    op.drop_table('RecipeTag')
    op.drop_table('RatingsFeedback')
    op.drop_table('Preferences')
    op.drop_table('User')
    op.drop_table('Tags')
    op.drop_table('Recipe')
    op.drop_table('Ingredient')
    # ### end Alembic commands ###
